### ISSUE TITLE
Метрополитен 1

### ISSUE THREAD

**Issue by mariscraps** [mariscraps/wasp-academy-HomeWork#1]
@vdetstvepil

**Comment by vdetstvepil** [comment]
**Файл Station.cs**
- 76, 86 и 95 строка. В этих методах тебе нужно просто возвращать bool'овскую переменную, а делать повторное сравнение - это избыточно. 
- 59 строка. Тебе на вход в конструктор поступает параметр transfers. А ты список transfers, который является полем класса, инициализируешь новым пустым. А нужно, чтобы элементы из входного списка перекочевали в список, который является полем класса.

**Comment by vdetstvepil** [comment]
Поправь ошибки, тогда зачту.

**Comment by mariscraps** [comment]
@vdetstvepil  
хорошо, поправила 
закоммитила как: Fixing Station

**Comment by vdetstvepil** [comment]
Принято.
