### ISSUE TITLE
Music Disc Store

### ISSUE THREAD

**Issue by mariscraps** [mariscraps/wasp-academy-HomeWork#2]
@vdetstvepil

**Comment by vdetstvepil** [comment]
- 12 строка. Интерфейс нужно вынести за пределы класса, а класс Disk унаследовать от этого интерфейса.

Доп. задание выполнено не полностью, но буду добрым и поставлю фулл стингер.

**Comment by vdetstvepil** [comment]
Принято (вместе с доп. заданием).

**Comment by mariscraps** [comment]
поправила, спасибо

**Comment by vdetstvepil** [comment]
👍
